server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://47.105.60.236:3306/lfy?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: lfy1756@163.com
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*/*Mapping.xml
  type-aliases-package: com.isabella.lee.*.pojo
